# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
warnings_are_errors: true

os:
  - linux
  - osx
  
env:
  - _R_CHECK_SYSTEM_CLOCK_=0

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
