# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
dist: trusty
sudo: required
cache: packages
warnings_are_errors: true

os:
  - linux
  #- osx Skipping osx build for now since 3.6 breaks the examples based on seed

r_packages:
  - covr

before_install:
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew install llvm; fi

after_success:
  - Rscript -e 'library(covr); codecov()'
